### PR TITLE
Logging

### LINKED ISSUE #22: Diagnostics tracking issue
# Issue 

Create a logging system to gather data about the robots runtime to help aid  in debugging / maintenance.

# Methods

- [x] Logging to a file (priority)
  - Different files for different things?
  - Non-competition only
  - Active only while ftc Dashboard is turned on 
 - [x] CSV data dumps (priority)
   - So that they can be imported into Excel

# Tracked data

- Voltage
- Motor positions
- Motor power
- Servo position
- Active APIs
- Robot absolute position (IMU / gyroscope)
- Any exceptions or errors
- Sensor data (no camera data directly, but output from OpenCV pipeline)
- Autonomous path?

# Steps
- Logging to file
- CSV Data stuff

### PR DESCRIPTION
**Pull request by Vif15**
This adds the Logging and Telemetry APIs. The Logging API deals with managing and writing csvs in the root folder. This API should only be used in non-competitive settings as it was not designed with efficiency in mind.

Closes #22.

### CODE REVIEW

**Review by cadenceforney — APPROVED** [review]
I aprove!

File: TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/Logging.kt [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+        res
+    }
+
+    /**
+     * Creates new files to log to (old files are deleted after every run).
+     */
+    fun createFile(fileName: String) {
+        if (RobotConfig.debug) {
+            fileHash[fileName] = BufferedWriter(FileWriter(File(BOTSBURGH_FOLDER, "/$fileName.csv"), true))
+            File(BOTSBURGH_FOLDER, "/$fileName.csv").createNewFile()
```
Comment (BD103) [inline TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/Logging.kt:39]: Shouldn't you create the file before you make a writer to it?

File: TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/Logging.kt [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+     * @param data Double data that is being logged
+     */
+    fun writeFile(
+        file: String,
+        data: Double,
+    ) {
+        if (RobotConfig.debug) {
+            fileHash.get(file)?.write("$data, ")
+            fileHash.get(file)?.write(opMode.runtime.toString())
+            fileHash.get(file)?.newLine()
```
Comment (BD103) [inline TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/Logging.kt]: Using the `?` operator will silently fail to write if the file was not created. Could you use `fileHash.get(file)!!` to throw an exception when the file is not found?

File: TeamCode/src/main/java/org/firstinspires/ftc/teamcode/teleop/LoggingTest.kt
Comment (BD103) [inline TeamCode/src/main/java/org/firstinspires/ftc/teamcode/teleop/LoggingTest.kt:1]: Can this be deleted?

File: TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/Telemetry.kt [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+        with(opMode.telemetry) {
+            addData("Status", "Running")
+            update()
+        }
+
+    fun sayStarted() =
+        with(opMode.telemetry) {
+            addData("Status", "Started")
+            update()
+        }
```
Comment (BD103) [inline TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/Telemetry.kt]: I'd rather delete these functions. I don't think they provide enough value, and can easily be copy-pasted.

**Review by BD103 — CHANGES_REQUESTED** [review]

File: TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/Logging.kt (hunk 1 above)
Comment (Vif15) [reply TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/Logging.kt:39]: it doesn't matter the order because the buffered writer points to the file path and not the file variable.

File: TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/Logging.kt (hunk 2 above)
Comment (Vif15) [reply TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/Logging.kt]: sure

File: TeamCode/src/main/java/org/firstinspires/ftc/teamcode/teleop/LoggingTest.kt
Comment (Vif15) [reply TeamCode/src/main/java/org/firstinspires/ftc/teamcode/teleop/LoggingTest.kt:1]: 👍

**Review by BD103 — APPROVED** [review]
Looks good for an MVP! I have a few follow up issues I want to create, but let's merge it!
